### ISSUE TITLE
Erreur synthaxe

### ISSUE THREAD

**Issue by Azerane** [alexpwf/abstractVM_unitest#1]
#> ./test_abstractVM.sh ~/Piscine/abstractVM
clean old project
module Done
/home/francoisguergadic/bin/abstractVM_unitest/tests.js:25
function execTest(test, file, neederr = false) {
                                      ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/fg/bin/abstractVM_unitest/node_modules/nodeunit/lib/nodeunit.js:75:37
    at /home/fg/bin/abstractVM_unitest/node_modules/nodeunit/deps/async.js:513:13
    at iterate (/home/fg/bin/abstractVM_unitest/node_modules/nodeunit/deps/async.js:123:13)

**Comment by alexpwf** [comment]
You need the version 6 or later of Node
